CREATE TABLE [dbo].[dct_stores] (
    [store_id]               INT           NOT NULL,
    [sales_id]               BIGINT        NOT NULL,
    [number]                 INT           NOT NULL,
    [name]                   VARCHAR (255) NOT NULL,
    [type_name]              VARCHAR (255) NOT NULL,
    [company_id]             INT           NOT NULL,
    [company_name]           VARCHAR (255) NOT NULL,
    [company_full_name]      VARCHAR (255) NOT NULL,
    [company_inn]            VARCHAR (255) NOT NULL,
    [branch_id]              INT           NOT NULL,
    [branch_name]            VARCHAR (255) NOT NULL,
    [unit_code]              VARCHAR (255) NULL,
    [unit_name]              VARCHAR (255) NULL,
    [address]                VARCHAR (255) NOT NULL,
    [subject_id]             INT           NULL,
    [subject_name]           VARCHAR (255) NULL,
    [city_name]              VARCHAR (255) NULL,
    [street_name]            VARCHAR (255) NOT NULL,
    [metro_name]             VARCHAR (255) NULL,
    [business_unit_id]       INT           NOT NULL,
    [business_unit_name]     VARCHAR (255) NOT NULL,
    [region_company_id]      INT           NOT NULL,
    [region_company_name]    VARCHAR (255) NOT NULL,
    [division_id]            INT           NOT NULL,
    [division_name]          VARCHAR (255) NOT NULL,
    [control_dir_id]         INT           NOT NULL,
    [control_dir_name]       VARCHAR (255) NOT NULL,
    [area_total]             FLOAT (53)    NOT NULL,
    [area_sales]             FLOAT (53)    NOT NULL,
    [is_disabled]            BIT           NULL,
    [disabled_date]          DATETIME      NOT NULL,
    [opening_date]           DATETIME      NOT NULL,
    [brand_id]               INT           NULL,
    [brand_name]             VARCHAR (255) NULL,
    [category_name]          VARCHAR (255) NOT NULL,
    [price_group_name]       VARCHAR (255) NOT NULL,
    [form_name]              VARCHAR (255) NULL,
    [format_name]            VARCHAR (255) NOT NULL,
    [location_name]          VARCHAR (255) NOT NULL,
    [is_franchise]           BIT           NOT NULL,
    [holding_name]           VARCHAR (255) NOT NULL,
    [lease_name]             VARCHAR (255) NOT NULL,
    [lease_end_date]         DATETIME      NOT NULL,
    [area_sublease]          MONEY         NOT NULL,
    [opening_type_name]      VARCHAR (255) NULL,
    [project_name]           VARCHAR (255) NULL,
    [open_year_type_name]    VARCHAR (255) NULL,
    [is_calc_tmz]            BIT           NOT NULL,
    [is_controller]          BIT           NULL,
    [is_video]               BIT           NULL,
    [is_pkkn]                BIT           NULL,
    [is_pku]                 BIT           NULL,
    [phone_1]                VARCHAR (255) NOT NULL,
    [phone_2]                VARCHAR (255) NOT NULL,
    [hours_monday]           VARCHAR (255) NOT NULL,
    [hours_tuesday]          VARCHAR (255) NOT NULL,
    [hours_wednesday]        VARCHAR (255) NOT NULL,
    [hours_thursday]         VARCHAR (255) NOT NULL,
    [hours_friday]           VARCHAR (255) NOT NULL,
    [hours_saturday]         VARCHAR (255) NOT NULL,
    [hours_sunday]           VARCHAR (255) NOT NULL,
    [db_id]                  INT           NULL,
    [jv_id]                  INT           NULL,
    [jv_name]                VARCHAR (255) NULL,
    [jv_cost_50]             FLOAT (53)    NULL,
    [jv_cost_50_500]         FLOAT (53)    NULL,
    [jv_cost_500]            FLOAT (53)    NULL,
    [jv_sale_50]             FLOAT (53)    NULL,
    [jv_sale_50_500]         FLOAT (53)    NULL,
    [jv_sale_500]            FLOAT (53)    NULL,
    [place_id]               INT           NULL,
    [Cluster_Id]             INT           NULL,
    [Cluster_Name]           VARCHAR (255) NULL,
    [opening_year_id]        AS            (datepart(year,[opening_date])),
    [opening_month_id]       AS            (datepart(year,[opening_date])*(100)+datepart(month,[opening_date])),
    [opening_month_name]     AS            (format([opening_date],'MMMM','ru-ru')),
    [opening_date_name]      AS            (CONVERT([varchar],[opening_date],(104))),
    [disabled_year_id]       AS            (datepart(year,[disabled_date])),
    [disabled_month_id]      AS            (datepart(year,[disabled_date])*(100)+datepart(month,[disabled_date])),
    [disabled_month_name]    AS            (format([disabled_date],'MMMM','ru-ru')),
    [disabled_date_name]     AS            (CONVERT([varchar],[disabled_date],(104))),
    [is_Coming_Soon]         BIT           NULL,
    [store_type_id]          INT           NULL,
    [store_type_name]        VARCHAR (255) NULL,
    [time_shift]             INT           NULL,
    [MedPoint]               INT           NULL,
    [MedLicense]             BIT           NULL,
    [HubStoreId]             INT           NULL,
    [region_management_id]   INT           NULL,
    [region_management_name] VARCHAR (255) NULL,
    [like_for_like]          BIT           NULL,
    [is_shop_in_shop]        BIT           NULL,
    [protek_supplier_id]     INT           NULL,
    [protek_supplier_name]   VARCHAR (255) NULL,
    [protek_warehouse_code]  VARCHAR (255) NULL,
    [ts]                     ROWVERSION    NOT NULL,
    [is_olap]                BIT           NULL,
    [board_id]               INT           NULL,
    [board_name]             VARCHAR (255) NULL,
    [cash_register_cnt]      INT           NULL,
    [country] varchar(100),
    [city] varchar(100)
);


GO

