CREATE TABLE [dbo].[fct_movement] (
    [date_id]                     INT              NULL,
    [time_id]                     INT              NULL,
    [store_id]                    INT              NOT NULL,
    [storehouse_id]               INT              NOT NULL,
    [doc_id]                      INT              NULL,
    [doc_type_id]                 INT              NULL,
    [supplier_id]                 INT              NULL,
    [good_id]                     INT              NOT NULL,
    [group_id]                    INT              NULL,
    [lot_id_old]                  INT              NULL,
    [expire_date_id]              INT              NULL,
    [scaling_ratio_id]            INT              NULL,
    [scale_id]                    INT              NULL,
    [row_count_id]                INT              NULL,
    [db_id]                       INT              NULL,
    [store_vat_id]                INT              NULL,
    [supplier_vat_id]             INT              NULL,
    [deduction_reason_id]         INT              NULL,
    [doc_reason_id]               INT              NULL,
    [quantity]                    MONEY            NULL,
    [prod_net]                    MONEY            NULL,
    [cost_net]                    MONEY            NULL,
    [cost_grs]                    MONEY            NULL,
    [sale_net]                    MONEY            NULL,
    [sale_grs]                    MONEY            NULL,
    [fact_net]                    MONEY            NULL,
    [fact_grs]                    MONEY            NULL,
    [cash_register_id]            INT              NULL,
    [user_id]                     INT              NULL,
    [service_id]                  INT              NULL,
    [buyer_id]                    INT              NULL,
    [loto_id]                     INT              NULL,
    [internet_order_id]           INT              NULL,
    [contractor_store_id]         INT              NULL,
    [trust_letter_id]             INT              NULL,
    [web_grs]                     MONEY            NULL,
    [web_net]                     MONEY            NULL,
    [sales_channel_id]            INT              NULL,
    [principal_supplier_id]       INT              NULL,
    [principal_store_id]          INT              NULL,
    [ef2_ID_DOCUMENT_ITEM_GLOBAL] UNIQUEIDENTIFIER NULL,
    [person_id]                   INT              NULL,
    [illiquid_type_id]            INT              NULL,
    [lot_id]                      BIGINT           NULL,
    [ext_movement_id]             BIGINT           NULL,
    [attribute_id]                INT              NULL,
    [lot_internet_order_id]       INT              NULL
);


GO

