CREATE TABLE [dbo].[fct_markaction] (
    [utc_date_id]                       INT              NULL,
    [utc_time_id]                       INT              NULL,
    [date_id]                           INT              NULL,
    [time_id]                           INT              NULL,
    [doc_id]                            INT              NULL,
    [doc_type_id]                       INT              NULL,
    [store_id]                          INT              NULL,
    [storehouse_id]                     INT              NULL,
    [cash_register_id]                  INT              NULL,
    [user_id]                           INT              NULL,
    [good_id]                           INT              NULL,
    [group_id]                          INT              NULL,
    [service_id]                        INT              NULL,
    [scaling_ratio_id]                  INT              NULL,
    [supplier_id]                       INT              NULL,
    [db_id]                             INT              NULL,
    [lot_id_old]                        INT              NULL,
    [expire_date_id]                    INT              NULL,
    [utc_expire_date_id]                INT              NULL,
    [markaction_id]                     INT              NULL,
    [oper_type_id]                      INT              NULL,
    [fin_item_id]                       INT              NULL,
    [compensation_id]                   INT              NULL,
    [discount_card_id]                  INT              NULL,
    [discount_program_id]               INT              NULL,
    [loyalty_id]                        INT              NULL,
    [internet_order_id]                 INT              NULL,
    [client_id]                         VARCHAR (255)    NULL,
    [trust_letter_id]                   INT              NULL,
    [store_vat_id]                      INT              NULL,
    [supplier_vat_id]                   INT              NULL,
    [fact_net]                          MONEY            NULL,
    [fact_grs]                          MONEY            NULL,
    [disc_net]                          MONEY            NULL,
    [disc_grs]                          MONEY            NULL,
    [proc_net]                          MONEY            NULL,
    [proc_grs]                          MONEY            NULL,
    [mindbox_ProcessingId]              TINYINT          NULL,
    [mindbox_CustomerActionMindboxId]   BIGINT           NULL,
    [quantity]                          MONEY            NULL,
    [ef2_ID_DISCOUNT2_MAKE_ITEM_GLOBAL] UNIQUEIDENTIFIER NULL,
    [ef2_PCX_TRANSACTION_ID]            VARCHAR (40)     NULL,
    [ef2_PCX_BARCODE]                   VARCHAR (128)    NULL,
    [recipe_id]                         BIGINT           NULL,
    [calc_proc_grs]                     MONEY            NULL,
    [calc_unit_quantity]                MONEY            NULL,
    [cheque_cost_net]                   MONEY            NULL,
    [cheque_cost_grs]                   MONEY            NULL,
    [cheque_sale_net]                   MONEY            NULL,
    [cheque_sale_grs]                   MONEY            NULL,
    [cheque_fact_net]                   MONEY            NULL,
    [cheque_fact_grs]                   MONEY            NULL,
    [lot_id]                            BIGINT           NULL,
    [ext_id]                            BIGINT           NULL,
    [attribute_id]                      INT              NULL
);


GO

